### ISSUE TITLE
Git

### ISSUE THREAD

**Issue by BrunaGravina** [elidianaandrade/elidianaandrade#2]
Olá,
Vim do bootcamp da ciência de dados com Python da DIO!

**Comment by VagnerEmanuel** [comment]
Olá!
Estou estudando o bootcamp ciência de dados com Python da DIO, sou um iniciante na programação, comecei a estudar em março deste ano, ainda estou me adaptando ao novo mundo, mas, estou gostando muito.

**Comment by elidianaandrade** [comment]
Olá Bruna e Vagner, prazer! 😊
